// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ActivateToolNode {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTIVATETOOLNODE
public:
    class ActivateToolNode& operator=(class ActivateToolNode const &) = delete;
    ActivateToolNode(class ActivateToolNode const &) = delete;
    ActivateToolNode() = delete;
#endif

public:
    /*0*/ virtual ~ActivateToolNode();
    /*1*/ virtual enum BehaviorStatus tick(class Actor &);
    /*2*/ virtual void initializeFromDefinition(class Actor &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ACTIVATETOOLNODE
#endif

};