// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ActorEventListener {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTOREVENTLISTENER
public:
    class ActorEventListener& operator=(class ActorEventListener const &) = delete;
    ActorEventListener(class ActorEventListener const &) = delete;
    ActorEventListener() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ACTOREVENTLISTENER
    MCVAPI enum class EventResult onActorAcquiredItem(class Actor &, class ItemInstance const &, unsigned int, enum class ItemAcquisitionMethod, class Actor *);
    MCVAPI enum class EventResult onActorAddEffect(struct ActorAddEffectEvent const &);
    MCVAPI enum class EventResult onActorAttack(class Actor &, class Actor &, int);
    MCVAPI enum class EventResult onActorAttackedActor(class Actor &, class Actor &);
    MCVAPI enum class EventResult onActorCarriedItemChanged(class Actor &, class ItemInstance const &, class ItemInstance const &, enum class HandSlot);
    MCVAPI enum class EventResult onActorCreated(class Actor &);
    MCVAPI enum class EventResult onActorDeath(class Actor &, class ActorDamageSource const &, enum class ActorType);
    MCVAPI enum class EventResult onActorDefinitionEventTriggered(struct ActorDefinitionEvent const &);
    MCVAPI enum class EventResult onActorDroppedItem(class Actor &, class ItemInstance const &);
    MCVAPI enum class EventResult onActorEquippedArmor(class Actor &, class ItemInstance const &, enum class ArmorSlot);
    MCVAPI enum class EventResult onActorGriefingBlock(struct ActorGriefingBlockEvent const &);
    MCVAPI enum class EventResult onActorHurt(struct ActorHurtEvent const &);
    MCVAPI enum class EventResult onActorKilled(struct ActorKilledEvent const &);
    MCVAPI enum class EventResult onActorMobInteraction(class Actor &, enum class MinecraftEventing::InteractionType, enum class ActorType);
    MCVAPI enum class EventResult onActorMove(class Actor &, class Vec3 const &);
    MCVAPI enum class EventResult onActorPlacedItem(class Actor &, class ItemInstance const &);
    MCVAPI enum class EventResult onActorPredictedMove(class Actor &, enum class MovePredictionType, class Vec3 const &);
    MCVAPI enum class EventResult onActorRemoveEffect(struct ActorRemoveEffectEvent const &);
    MCVAPI enum class EventResult onActorRemoved(class Actor &);
    MCVAPI enum class EventResult onActorSneakChanged(class Actor &, bool);
    MCVAPI enum class EventResult onActorStartRiding(class Actor &, class Actor &);
    MCVAPI enum class EventResult onActorStopRiding(class Actor &, bool, bool, bool);
    MCVAPI enum class EventResult onActorTargetAcquired(class Actor &, class Actor &);
    MCVAPI enum class EventResult onActorTeleported(class Actor &);
    MCVAPI enum class EventResult onActorTick(class Actor &);
    MCVAPI enum class EventResult onActorUseItem(class Actor &, class ItemInstance const &, enum class ItemUseMethod);
    MCVAPI enum class EventResult onActorUseItemOn(class Actor &, class ItemStack const &, class BlockPos const &, unsigned char);
    MCVAPI enum class EventResult onKnockBack(struct KnockBackEvent const &);
    MCVAPI enum class EventResult onMountTaming(struct MountTamingEvent const &);
    MCVAPI enum class EventResult onProjectileHit(struct ProjectileHitEvent const &);
#endif

};