// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA


#undef BEFORE_EXTRA

class ActorTerrainInterlockData {

#define AFTER_EXTRA
public:
    enum class VisibilityState : unsigned char {
        InitialNotVisible = 0x0,
        Visible = 0x1,
        DelayedDestructionNotVisible = 0x2,
    };
	
    VisibilityState mRenderVisibilityState;
    std::chrono::time_point<std::chrono::steady_clock, std::chrono::duration<__int64, std::ratio<1, 1000000000>>> mCreationTime;
    bool mHasBeenDelayedDeleted;
	
#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTORTERRAININTERLOCKDATA
public:
    class ActorTerrainInterlockData& operator=(class ActorTerrainInterlockData const &) = delete;
    ActorTerrainInterlockData(class ActorTerrainInterlockData const &) = delete;
    ActorTerrainInterlockData() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ACTORTERRAININTERLOCKDATA
#endif
    MCAPI void setCreationTime();

};