// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ActorRemoveEffectEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTORREMOVEEFFECTEVENT
public:
    struct ActorRemoveEffectEvent& operator=(struct ActorRemoveEffectEvent const &) = delete;
    ActorRemoveEffectEvent(struct ActorRemoveEffectEvent const &) = delete;
    ActorRemoveEffectEvent() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ACTORREMOVEEFFECTEVENT
#endif
    MCAPI ~ActorRemoveEffectEvent();

};