// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AddOceanTemperatureLayer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ADDOCEANTEMPERATURELAYER
public:
    class AddOceanTemperatureLayer& operator=(class AddOceanTemperatureLayer const &) = delete;
    AddOceanTemperatureLayer(class AddOceanTemperatureLayer const &) = delete;
    AddOceanTemperatureLayer() = delete;
#endif

public:
    /*0*/ virtual ~AddOceanTemperatureLayer();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual class LayerDetails::TransferData<enum BiomeTemperatureCategory> _allocateAndFill(unsigned __int64, int, int, unsigned int, unsigned int) const;
    /*3*/ virtual void _fillArea(class LayerDetails::WorkingData<enum BiomeTemperatureCategory, char> &, int, int, int, int) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ADDOCEANTEMPERATURELAYER
#endif

};