// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AgentCommandSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_AGENTCOMMANDSYSTEM
public:
    class AgentCommandSystem& operator=(class AgentCommandSystem const &) = delete;
    AgentCommandSystem(class AgentCommandSystem const &) = delete;
    AgentCommandSystem() = delete;
#endif

public:
    /*0*/ virtual ~AgentCommandSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_AGENTCOMMANDSYSTEM
#endif

};