// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AngryComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ANGRYCOMPONENT
public:
    class AngryComponent& operator=(class AngryComponent const &) = delete;
    AngryComponent(class AngryComponent const &) = delete;
    AngryComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ANGRYCOMPONENT
#endif
    MCAPI AngryComponent(class AngryComponent &&);
    MCAPI bool canAttack(class Mob &, class Mob *, class Actor *, bool, bool);
    MCAPI class AngryComponent & operator=(class AngryComponent &&);
    MCAPI void restartTimer(class Mob &);
    MCAPI ~AngryComponent();

};