// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AreaAttackComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_AREAATTACKCOMPONENT
public:
    class AreaAttackComponent& operator=(class AreaAttackComponent const &) = delete;
    AreaAttackComponent(class AreaAttackComponent const &) = delete;
    AreaAttackComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_AREAATTACKCOMPONENT
#endif
    MCAPI class AreaAttackComponent & operator=(class AreaAttackComponent &&);
    MCAPI ~AreaAttackComponent();

};