// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace Automation {

#define AFTER_EXTRA
class AutomationClient;
#undef AFTER_EXTRA
    MCAPI extern char const * Body;
    MCAPI extern char const * BodyData;
    MCAPI extern char const * Header;
    MCAPI extern char const * HeaderData;
    MCAPI extern char const * MsgPurpose;
    MCAPI extern char const * RequestId;
    MCAPI extern char const * StatusCode;
    MCAPI extern char const * StatusMsg;
    MCAPI extern char const * VersionData;

};