// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BaseMoveToBlockGoal {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BASEMOVETOBLOCKGOAL
public:
    class BaseMoveToBlockGoal& operator=(class BaseMoveToBlockGoal const &) = delete;
    BaseMoveToBlockGoal(class BaseMoveToBlockGoal const &) = delete;
    BaseMoveToBlockGoal() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BASEMOVETOBLOCKGOAL
    MCVAPI void _moveToBlock();
    MCVAPI bool canContinueToUse();
    MCVAPI bool canUse();
    MCVAPI bool findTargetBlock();
    MCVAPI ~BaseMoveToBlockGoal();
#endif

};