// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "LevelContainerManagerModel.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BeaconContainerManagerModel : public LevelContainerManagerModel {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BEACONCONTAINERMANAGERMODEL
public:
    class BeaconContainerManagerModel& operator=(class BeaconContainerManagerModel const &) = delete;
    BeaconContainerManagerModel(class BeaconContainerManagerModel const &) = delete;
    BeaconContainerManagerModel() = delete;
#endif

public:
    /*0*/ virtual ~BeaconContainerManagerModel();
    /*6*/ virtual std::vector<class ItemStack> getItemCopies() const;
    /*7*/ virtual void setSlot(int, class ItemStack const &, bool);
    /*8*/ virtual class ItemStack const & getSlot(int) const;
    /*12*/ virtual class ContainerScreenContext _postInit();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BEACONCONTAINERMANAGERMODEL
#endif

//private:
    MCAPI void _resetSelectionState();

private:

};