// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BinaryHeap {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BINARYHEAP
public:
    class BinaryHeap& operator=(class BinaryHeap const &) = delete;
    BinaryHeap(class BinaryHeap const &) = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BINARYHEAP
#endif
    MCAPI BinaryHeap();
    MCAPI class PathfinderNode * insert(class PathfinderNode *);
    MCAPI ~BinaryHeap();

//private:
    MCAPI void downHeap(int);
    MCAPI void upHeap(int);

private:

};