// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here
enum class VanillaBiomeTypes : int {
    Beach = 0x0,
    Desert = 0x1,
    ExtremeHills = 0x2,
    Flat = 0x3,
    Forest = 0x4,
    Hell = 0x5,
    Ice = 0x6,
    Jungle = 0x7,
    Mesa = 0x8,
    MushroomIsland = 0x9,
    Ocean = 0xA,
    Plain = 0xB,
    River = 0xC,
    Savanna = 0xD,
    StoneBeach = 0xE,
    Swamp = 0xF,
    Taiga = 0x10,
    TheEnd = 0x11,
    DataDriven = 0x12,
};
#undef BEFORE_EXTRA

class Biome {

#define AFTER_EXTRA
    // Add Member There
public:
    enum class BiomeTempCategory;
    LIAPI int getId() const;
    LIAPI std::string const& getName() const;
    LIAPI static Biome* fromId(int id);
    LIAPI static Biome* fromName(std::string const& name);
    LIAPI static std::vector<Biome*> getBiomesByType(VanillaBiomeTypes type);

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BIOME
public:
    class Biome& operator=(class Biome const &) = delete;
    Biome(class Biome const &) = delete;
    Biome() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BIOME
#endif
    MCAPI Biome(int);
    MCAPI class Biome & addTag(class HashedString, class TagRegistry<struct IDType<struct BiomeTagIDType>, struct IDType<struct BiomeTagSetIDType>> &);
    MCAPI enum class VanillaBiomeTypes getBiomeType() const;
    MCAPI int getFoliageColor(class BlockPos const &) const;
    MCAPI int getMapFoliageColor(class BlockPos const &) const;
    MCAPI int getMapGrassColor(class BlockPos const &) const;
    MCAPI float getTemperature(class BlockSource const &, class BlockPos const &) const;
    MCAPI enum class Biome::BiomeTempCategory getTemperatureCategory() const;
    MCAPI float getTemperatureWorldGen(class BlockPos const &, short) const;
    MCAPI bool hasTag(unsigned __int64, class TagRegistry<struct IDType<struct BiomeTagIDType>, struct IDType<struct BiomeTagSetIDType>> const &) const;
    MCAPI bool hasTag(struct IDType<struct BiomeTagIDType> const &, class TagRegistry<struct IDType<struct BiomeTagIDType>, struct IDType<struct BiomeTagSetIDType>> const &) const;
    MCAPI bool hasTag(class WellKnownTagID const &) const;
    MCAPI void initEntity(class EntityRegistryOwned &);
    MCAPI bool isHumid() const;
    MCAPI class Biome & setColor(int);
    MCAPI class Biome & setColor(int, bool);
    MCAPI class Biome & setMapWaterColor(int);
    MCAPI void writePacketData(class CompoundTag &, class TagRegistry<struct IDType<struct BiomeTagIDType>, struct IDType<struct BiomeTagSetIDType>> &);
    MCAPI static class gsl::basic_string_span<char const, -1> const BACKCOMPAT_FOG_NAME;
    MCAPI static class mce::Color const DEFAULT_FOG_COLOR;
    MCAPI static class gsl::basic_string_span<char const, -1> const DEFAULT_FOG_ID;
    MCAPI static class mce::Color const DEFAULT_UNDERWATER_COLOR;
    MCAPI static class mce::Color const DEFAULT_WATER_COLOR;
    MCAPI static float const RAIN_TEMP_THRESHOLD;

};