// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct BlockStateDefinition {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BLOCKSTATEDEFINITION
public:
    struct BlockStateDefinition& operator=(struct BlockStateDefinition const &) = delete;
    BlockStateDefinition(struct BlockStateDefinition const &) = delete;
    BlockStateDefinition() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BLOCKSTATEDEFINITION
#endif
    MCAPI struct BlockStateDefinition & operator=(struct BlockStateDefinition &&);
    MCAPI ~BlockStateDefinition();

//private:
    MCAPI void _copy(struct BlockStateDefinition const &);

};