// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct BlockPlacementCondition {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BLOCKPLACEMENTCONDITION
public:
    struct BlockPlacementCondition& operator=(struct BlockPlacementCondition const &) = delete;
    BlockPlacementCondition(struct BlockPlacementCondition const &) = delete;
    BlockPlacementCondition() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BLOCKPLACEMENTCONDITION
#endif
    MCAPI void _addBlockDescriptor(class BlockDescriptor const &);
    MCAPI ~BlockPlacementCondition();

};