// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BossSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BOSSSYSTEM
public:
    class BossSystem& operator=(class BossSystem const &) = delete;
    BossSystem(class BossSystem const &) = delete;
    BossSystem() = delete;
#endif

public:
    /*0*/ virtual ~BossSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BOSSSYSTEM
#endif

};