// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BreedableComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BREEDABLECOMPONENT
public:
    class BreedableComponent& operator=(class BreedableComponent const &) = delete;
    BreedableComponent(class BreedableComponent const &) = delete;
    BreedableComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BREEDABLECOMPONENT
#endif
    MCAPI bool canMate(class Actor const &, class Actor const &) const;
    MCAPI bool getInteraction(class Actor &, class Player &, class ActorInteraction &);
    MCAPI bool meetsSittingRequirements(class Actor const &) const;
    MCAPI void readAdditionalSaveData(class Actor &, class CompoundTag const &, class DataLoadHelper &);
    MCAPI void setInLove(class Actor &, class Player const *);

//private:
    MCAPI void _handleMate(class Actor &, class Actor &);
    MCAPI void _handlePregnancy(class Actor &, class Actor &);
    MCAPI bool _meetsEnvironmentRequirements(class Actor &) const;

private:

};