// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BribeableSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BRIBEABLESYSTEM
public:
    class BribeableSystem& operator=(class BribeableSystem const &) = delete;
    BribeableSystem(class BribeableSystem const &) = delete;
    BribeableSystem() = delete;
#endif

public:
    /*0*/ virtual ~BribeableSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BRIBEABLESYSTEM
#endif

};