// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct CommandOriginData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_COMMANDORIGINDATA
public:
    struct CommandOriginData& operator=(struct CommandOriginData const &) = delete;
    CommandOriginData(struct CommandOriginData const &) = delete;
    CommandOriginData() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_COMMANDORIGINDATA
#endif
    MCAPI ~CommandOriginData();

};