// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ComponentDescription {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_COMPONENTDESCRIPTION
public:
    struct ComponentDescription& operator=(struct ComponentDescription const &) = delete;
    ComponentDescription(struct ComponentDescription const &) = delete;
    ComponentDescription() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_COMPONENTDESCRIPTION
    MCVAPI ~ComponentDescription();
#endif

};