// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ContainerValidation {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CONTAINERVALIDATION
public:
    class ContainerValidation& operator=(class ContainerValidation const &) = delete;
    ContainerValidation(class ContainerValidation const &) = delete;
    ContainerValidation() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CONTAINERVALIDATION
#endif
    MCAPI static void assignValidationDelegates(class SparseContainer &, enum ContainerEnumName, class ContainerScreenContext const &);

//private:
    MCAPI static void assignValidForSlotContainerDelegate(class SparseContainer &, enum ContainerEnumName, class ContainerScreenContext const &);

private:

};