// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct CraftingTableComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CRAFTINGTABLECOMPONENT
public:
    struct CraftingTableComponent& operator=(struct CraftingTableComponent const &) = delete;
    CraftingTableComponent(struct CraftingTableComponent const &) = delete;
    CraftingTableComponent() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CRAFTINGTABLECOMPONENT
#endif
    MCAPI struct CraftingTableComponent & operator=(struct CraftingTableComponent &&);
    MCAPI ~CraftingTableComponent();

};