// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Core.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace CryptoUtils {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI std::string getDirectroyChecksum(class Core::Path const &);
    MCAPI std::string getFileChecksum(class Core::Path const &);

};