// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct DamageSensorTrigger {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_DAMAGESENSORTRIGGER
public:
    struct DamageSensorTrigger& operator=(struct DamageSensorTrigger const &) = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_DAMAGESENSORTRIGGER
#endif
    MCAPI DamageSensorTrigger(struct DamageSensorTrigger const &);
    MCAPI DamageSensorTrigger();
    MCAPI void setCause(std::string const &);
    MCAPI ~DamageSensorTrigger();

};