// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class DirtyTicksCounter {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_DIRTYTICKSCOUNTER
public:
    class DirtyTicksCounter& operator=(class DirtyTicksCounter const &) = delete;
    DirtyTicksCounter(class DirtyTicksCounter const &) = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_DIRTYTICKSCOUNTER
#endif
    MCAPI DirtyTicksCounter();

};