// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace EducationMetadataUtils {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI struct EducationMetadata parse(std::string const &, std::vector<std::string> &, class PackReport &);
    MCAPI void parseEducationMetadataContent(class Json::Value const &, std::vector<std::string> &, struct EducationMetadata &, class PackReport &);

};