// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct EducationLocalLevelSettings {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EDUCATIONLOCALLEVELSETTINGS
public:
    EducationLocalLevelSettings(struct EducationLocalLevelSettings const &) = delete;
    EducationLocalLevelSettings() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EDUCATIONLOCALLEVELSETTINGS
#endif
    MCAPI struct EducationLocalLevelSettings & operator=(struct EducationLocalLevelSettings const &);
    MCAPI ~EducationLocalLevelSettings();

};