// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class EmptyActorGameplayHandler {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EMPTYACTORGAMEPLAYHANDLER
public:
    class EmptyActorGameplayHandler& operator=(class EmptyActorGameplayHandler const &) = delete;
    EmptyActorGameplayHandler(class EmptyActorGameplayHandler const &) = delete;
    EmptyActorGameplayHandler() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EMPTYACTORGAMEPLAYHANDLER
    MCVAPI enum class HandlerResult handleActorAddEffect(struct ActorAddEffectEvent const &);
    MCVAPI enum class HandlerResult handleActorDefinitionEventTriggered(struct ActorDefinitionEvent const &);
    MCVAPI struct GameplayHandlerResult<enum class CoordinatorResult> handleActorGriefingBlock(struct ActorGriefingBlockEvent const &);
    MCVAPI enum class HandlerResult handleActorHurt(struct ActorHurtEvent const &);
    MCVAPI enum class HandlerResult handleActorKilled(struct ActorKilledEvent const &);
    MCVAPI enum class HandlerResult handleActorRemoveEffect(struct ActorRemoveEffectEvent const &);
    MCVAPI enum class HandlerResult handleKnockBack(struct KnockBackEvent const &);
    MCVAPI enum class HandlerResult handleMountTaming(struct MountTamingEvent const &);
    MCVAPI struct GameplayHandlerResult<enum class CoordinatorResult> handleProjectileHit(struct ProjectileHitEvent const &);
#endif

};