// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class EnchantWithLevelsFunction {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ENCHANTWITHLEVELSFUNCTION
public:
    class EnchantWithLevelsFunction& operator=(class EnchantWithLevelsFunction const &) = delete;
    EnchantWithLevelsFunction(class EnchantWithLevelsFunction const &) = delete;
    EnchantWithLevelsFunction() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ENCHANTWITHLEVELSFUNCTION
    MCVAPI void apply(class ItemStack &, class Random &, class LootTableContext &);
    MCVAPI void apply(class ItemInstance &, class Random &, class LootTableContext &);
    MCVAPI int apply(class ItemStack &, class Random &, struct Trade const &, class LootTableContext &);
    MCVAPI int apply(class ItemInstance &, class Random &, struct Trade const &, class LootTableContext &);
#endif

};