// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "NetworkPeer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class EncryptedNetworkPeer : public NetworkPeer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ENCRYPTEDNETWORKPEER
public:
    class EncryptedNetworkPeer& operator=(class EncryptedNetworkPeer const &) = delete;
    EncryptedNetworkPeer(class EncryptedNetworkPeer const &) = delete;
    EncryptedNetworkPeer() = delete;
#endif

public:
    /*0*/ virtual ~EncryptedNetworkPeer();
    /*1*/ virtual void sendPacket(std::string const &, enum class NetworkPeer::Reliability, int, unsigned short, enum class Compressibility);
    /*2*/ virtual enum class NetworkPeer::DataStatus receivePacket(std::string &);
    /*3*/ virtual struct NetworkPeer::NetworkStatus getNetworkStatus();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ENCRYPTEDNETWORKPEER
#endif
    MCAPI void enableEncryption(std::string const &);

};