// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"
#include "JsonUtil.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class EquippableDefinition {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EQUIPPABLEDEFINITION
public:
    class EquippableDefinition& operator=(class EquippableDefinition const &) = delete;
    EquippableDefinition(class EquippableDefinition const &) = delete;
    EquippableDefinition() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EQUIPPABLEDEFINITION
#endif
    MCAPI void deserializeData(class Json::Value &);
    MCAPI void serializeData(class Json::Value &) const;
    MCAPI ~EquippableDefinition();
    MCAPI static void buildSchema(class std::shared_ptr<class JsonUtil::JsonSchemaObjectNode<class JsonUtil::EmptyClass, class EquippableDefinition>> &);

};