// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct FireImmuneDefinition {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_FIREIMMUNEDEFINITION
public:
    struct FireImmuneDefinition& operator=(struct FireImmuneDefinition const &) = delete;
    FireImmuneDefinition(struct FireImmuneDefinition const &) = delete;
    FireImmuneDefinition() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_FIREIMMUNEDEFINITION
#endif

//private:
    MCAPI void _setFlags(class EntityContext &, bool);

};