// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"
#include "ActorCommandOrigin.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class GameMasterEntityServerCommandOrigin : public ActorCommandOrigin {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_GAMEMASTERENTITYSERVERCOMMANDORIGIN
public:
    class GameMasterEntityServerCommandOrigin& operator=(class GameMasterEntityServerCommandOrigin const &) = delete;
    GameMasterEntityServerCommandOrigin(class GameMasterEntityServerCommandOrigin const &) = delete;
    GameMasterEntityServerCommandOrigin() = delete;
#endif

public:
    /*0*/ virtual ~GameMasterEntityServerCommandOrigin();
    /*8*/ virtual enum class CommandPermissionLevel getPermissionsLevel() const;
    /*9*/ virtual std::unique_ptr<class CommandOrigin> clone() const;
    /*17*/ virtual bool isSelectorExpansionAllowed() const;
    /*21*/ virtual enum class CommandOriginType getOriginType() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_GAMEMASTERENTITYSERVERCOMMANDORIGIN
#endif

};