// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class GameSession {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_GAMESESSION
public:
    class GameSession& operator=(class GameSession const &) = delete;
    GameSession(class GameSession const &) = delete;
    GameSession() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_GAMESESSION
#endif
    MCAPI GameSession(class NetworkHandler &, std::unique_ptr<class ServerNetworkHandler>, class LoopbackPacketSender &, std::unique_ptr<class NetEventCallback>, std::unique_ptr<class Level>, unsigned char);
    MCAPI void setLevel(std::unique_ptr<class Level>);

};