// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class GroupSizeSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_GROUPSIZESYSTEM
public:
    class GroupSizeSystem& operator=(class GroupSizeSystem const &) = delete;
    GroupSizeSystem(class GroupSizeSystem const &) = delete;
    GroupSizeSystem() = delete;
#endif

public:
    /*0*/ virtual ~GroupSizeSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_GROUPSIZESYSTEM
#endif

//private:
    MCAPI void _tickComponent(class EntityContext &, class FlagComponent<struct ActorTickedFlag> &, class ActorComponent &, class GroupSizeComponent &);

private:

};