// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class HomeSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_HOMESYSTEM
public:
    class HomeSystem& operator=(class HomeSystem const &) = delete;
    HomeSystem(class HomeSystem const &) = delete;
    HomeSystem() = delete;
#endif

public:
    /*0*/ virtual ~HomeSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_HOMESYSTEM
#endif

//private:
    MCAPI void _tickComponent(class ViewedEntityContextT<class EntityContext, class FlagComponent<struct ActorTickedFlag>, class ActorComponent, class HomeComponent> &);

private:

};