// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class HurtOnConditionSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_HURTONCONDITIONSYSTEM
public:
    class HurtOnConditionSystem& operator=(class HurtOnConditionSystem const &) = delete;
    HurtOnConditionSystem(class HurtOnConditionSystem const &) = delete;
    HurtOnConditionSystem() = delete;
#endif

public:
    /*0*/ virtual ~HurtOnConditionSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_HURTONCONDITIONSYSTEM
#endif

};