// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class IAppPlatform {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_IAPPPLATFORM
public:
    class IAppPlatform& operator=(class IAppPlatform const &) = delete;
    IAppPlatform(class IAppPlatform const &) = delete;
    IAppPlatform() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_IAPPPLATFORM
    MCVAPI ~IAppPlatform();
#endif

};