// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class IllagerBeastBlockedComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ILLAGERBEASTBLOCKEDCOMPONENT
public:
    class IllagerBeastBlockedComponent& operator=(class IllagerBeastBlockedComponent const &) = delete;
    IllagerBeastBlockedComponent(class IllagerBeastBlockedComponent const &) = delete;
    IllagerBeastBlockedComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ILLAGERBEASTBLOCKEDCOMPONENT
#endif
    MCAPI void onBlocked(class Actor &, class ActorDamageSource const &, class Actor &);

};