// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class InteractSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_INTERACTSYSTEM
public:
    class InteractSystem& operator=(class InteractSystem const &) = delete;
    InteractSystem(class InteractSystem const &) = delete;
    InteractSystem() = delete;
#endif

public:
    /*0*/ virtual ~InteractSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_INTERACTSYSTEM
#endif

};