// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class IScreenChangedEventing {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ISCREENCHANGEDEVENTING
public:
    class IScreenChangedEventing& operator=(class IScreenChangedEventing const &) = delete;
    IScreenChangedEventing(class IScreenChangedEventing const &) = delete;
    IScreenChangedEventing() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ISCREENCHANGEDEVENTING
#endif

};