// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct IsSpawnableDescription {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ISSPAWNABLEDESCRIPTION
public:
    struct IsSpawnableDescription& operator=(struct IsSpawnableDescription const &) = delete;
    IsSpawnableDescription(struct IsSpawnableDescription const &) = delete;
    IsSpawnableDescription() = delete;
#endif
public:
    /*0*/ virtual ~IsSpawnableDescription();
    /*1*/ virtual char const * getJsonName() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ISSPAWNABLEDESCRIPTION
#endif

};