// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace ItemTransactionLogger {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI void log(std::string);
    MCAPI void log(class ItemStack const &, std::string);
    MCAPI void log(class InventoryAction const &, std::string);
    MCAPI void log(class ItemStackResponsePacket const &, std::string);
    MCAPI void log(class InventoryTransactionPacket const &, std::string);

};