// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ItemLockHelper {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ITEMLOCKHELPER
public:
    class ItemLockHelper& operator=(class ItemLockHelper const &) = delete;
    ItemLockHelper(class ItemLockHelper const &) = delete;
    ItemLockHelper() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ITEMLOCKHELPER
#endif
    MCAPI static enum ItemLockMode getItemLockMode(class ItemStackBase const &);
    MCAPI static bool isItemLocked(class ItemStackBase const &);
    MCAPI static bool shouldKeepOnDeath(class ItemStackBase const &);

//private:
    MCAPI static bool _parseItemLockMode(class ItemStackBase &, class Json::Value const &);

private:

};