// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ItemData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ITEMDATA
public:
    struct ItemData& operator=(struct ItemData const &) = delete;
    ItemData(struct ItemData const &) = delete;
    ItemData() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ITEMDATA
#endif
    MCAPI ~ItemData();

};