// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace ItemColorUtil {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI std::string const & getName(enum ItemColor);

};