// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class KeyManager {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_KEYMANAGER
public:
    class KeyManager& operator=(class KeyManager const &) = delete;
    KeyManager(class KeyManager const &) = delete;
    KeyManager() = delete;
#endif

public:
    /*0*/ virtual ~KeyManager();
    /*1*/ virtual bool isValid() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_KEYMANAGER
#endif
    MCAPI KeyManager(std::string const &, enum Crypto::Asymmetric::System);

};