// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class LayerBiomeSource {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LAYERBIOMESOURCE
public:
    class LayerBiomeSource& operator=(class LayerBiomeSource const &) = delete;
    LayerBiomeSource(class LayerBiomeSource const &) = delete;
    LayerBiomeSource() = delete;
#endif

public:
    /*0*/ virtual ~LayerBiomeSource();
    /*1*/ virtual void fillBiomes(class LevelChunk &) const;
    /*2*/ virtual class BiomeArea getBiomeArea(class BoundingBox const &, unsigned int) const = 0;
    /*3*/ virtual bool containsOnly(int, int, int, class gsl::span<int const, -1>) const = 0;
    /*4*/ virtual class Biome const * getBiome(int, int) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LAYERBIOMESOURCE
#endif

//protected:
    MCAPI void _getBiomeArea(class Layer<class Biome *> const &, class BoundingBox const &, unsigned int, class BiomeArea &) const;

protected:

};