// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ListTagIntAdder {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LISTTAGINTADDER
public:
    class ListTagIntAdder& operator=(class ListTagIntAdder const &) = delete;
    ListTagIntAdder(class ListTagIntAdder const &) = delete;
    ListTagIntAdder() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LISTTAGINTADDER
#endif
    MCAPI class ListTagIntAdder & operator()(int);
    MCAPI ~ListTagIntAdder();

};