// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "LookAtActorGoal.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class LookAtTradingPlayerGoal : public LookAtActorGoal {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LOOKATTRADINGPLAYERGOAL
public:
    class LookAtTradingPlayerGoal& operator=(class LookAtTradingPlayerGoal const &) = delete;
    LookAtTradingPlayerGoal(class LookAtTradingPlayerGoal const &) = delete;
    LookAtTradingPlayerGoal() = delete;
#endif

public:
    /*0*/ virtual ~LookAtTradingPlayerGoal();
    /*1*/ virtual bool canUse();
    /*2*/ virtual bool canContinueToUse();
    /*3*/ virtual void __unk_vfn_3();
    /*7*/ virtual void appendDebugInfo(std::string &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LOOKATTRADINGPLAYERGOAL
#endif

};