// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Enchant.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MendingEnchant : public Enchant {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MENDINGENCHANT
public:
    class MendingEnchant& operator=(class MendingEnchant const &) = delete;
    MendingEnchant(class MendingEnchant const &) = delete;
    MendingEnchant() = delete;
#endif

public:
    /*0*/ virtual ~MendingEnchant();
    /*2*/ virtual int getMinCost(int) const;
    /*3*/ virtual int getMaxCost(int) const;
    /*5*/ virtual int getMaxLevel() const;
    /*10*/ virtual void __unk_vfn_10();
    /*11*/ virtual void __unk_vfn_11();
    /*12*/ virtual bool isTreasureOnly() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MENDINGENCHANT
#endif

};