// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MobEffectSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MOBEFFECTSYSTEM
public:
    class MobEffectSystem& operator=(class MobEffectSystem const &) = delete;
    MobEffectSystem(class MobEffectSystem const &) = delete;
    MobEffectSystem() = delete;
#endif

public:
    /*0*/ virtual ~MobEffectSystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MOBEFFECTSYSTEM
#endif

//private:
    MCAPI void _tickComponent(class EntityContext &, class FlagComponent<struct ActorTickedFlag> &, class ActorComponent &, class MobEffectComponent &);

private:

};