// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MolangVariable {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MOLANGVARIABLE
public:
    class MolangVariable& operator=(class MolangVariable const &) = delete;
    MolangVariable(class MolangVariable const &) = delete;
    MolangVariable() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MOLANGVARIABLE
#endif
    MCAPI MolangVariable(enum class MolangVariableIndex, class HashedString, struct MolangScriptArg);
    MCAPI ~MolangVariable();
    MCAPI static enum class MolangVariableIndex getVariableIndex(class HashedString const &);
    MCAPI static enum class MolangVariableIndex getVariableIndex(unsigned __int64);
    MCAPI static enum class MolangVariableIndex getVariableIndex(unsigned __int64, char const *, bool);
    MCAPI static class HashedString const & getVariableName(enum class MolangVariableIndex);
    MCAPI static void initVariableMaps();
    MCAPI static bool isValidName(char const *);

//private:
    MCAPI static class std::recursive_mutex & _getMolangVariableIndexLock();
    MCAPI static void _resetToLowWaterMark();
    MCAPI static void _updateLowWaterMark();

private:
    MCAPI static bool mHasSetWatermark;
    MCAPI static class std::unordered_map<enum class MolangVariableIndex, class HashedString, struct std::hash<enum class MolangVariableIndex>, struct std::equal_to<enum class MolangVariableIndex>, class std::allocator<struct std::pair<enum class MolangVariableIndex const, class HashedString>>> mIndexToVariableNameMap;
    MCAPI static class std::unordered_map<enum class MolangVariableIndex, class HashedString, struct std::hash<enum class MolangVariableIndex>, struct std::equal_to<enum class MolangVariableIndex>, class std::allocator<struct std::pair<enum class MolangVariableIndex const, class HashedString>>> mIndexToVariableNameMap_LowWaterMark;
    MCAPI static class std::unordered_map<unsigned __int64, enum class MolangVariableIndex, struct std::hash<unsigned __int64>, struct std::equal_to<unsigned __int64>, class std::allocator<struct std::pair<unsigned __int64 const, enum class MolangVariableIndex>>> mVariableNameToIndexMap;
    MCAPI static class std::unordered_map<unsigned __int64, enum class MolangVariableIndex, struct std::hash<unsigned __int64>, struct std::equal_to<unsigned __int64>, class std::allocator<struct std::pair<unsigned __int64 const, enum class MolangVariableIndex>>> mVariableNameToIndexMap_LowWaterMark;

};