// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class NavigationComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_NAVIGATIONCOMPONENT
public:
    class NavigationComponent& operator=(class NavigationComponent const &) = delete;
    NavigationComponent(class NavigationComponent const &) = delete;
    NavigationComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_NAVIGATIONCOMPONENT
#endif
    MCAPI NavigationComponent(class NavigationComponent &&);
    MCAPI void initMultiTypeNavigationComponent(class Mob &, class ActorDefinitionDescriptor &);
    MCAPI void initializeFromDefinition(class Mob &, struct NavigationDescription *);
    MCAPI bool moveTo(class Mob &, std::unique_ptr<class Path>, float);
    MCAPI class NavigationComponent & operator=(class NavigationComponent &&);
    MCAPI void setInternalType(std::unique_ptr<class PathNavigation>);
    MCAPI ~NavigationComponent();

};