// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class OpenDoorAnnotationComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_OPENDOORANNOTATIONCOMPONENT
public:
    class OpenDoorAnnotationComponent& operator=(class OpenDoorAnnotationComponent const &) = delete;
    OpenDoorAnnotationComponent(class OpenDoorAnnotationComponent const &) = delete;
    OpenDoorAnnotationComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_OPENDOORANNOTATIONCOMPONENT
#endif
    MCAPI OpenDoorAnnotationComponent(class OpenDoorAnnotationComponent &&);
    MCAPI void checkPath(class Mob &);

//private:
    MCAPI void _cleanUp(class Mob const &);
    MCAPI void _tryToggleDoorState(class Block const &, class Mob const &, class BlockPos) const;

private:

};