// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class PackSourceReport {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PACKSOURCEREPORT
public:
    PackSourceReport() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PACKSOURCEREPORT
#endif
    MCAPI PackSourceReport(class PackSourceReport const &);
    MCAPI class PackSourceReport & operator=(class PackSourceReport const &);
    MCAPI ~PackSourceReport();

};