// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct PageContent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PAGECONTENT
public:
    struct PageContent& operator=(struct PageContent const &) = delete;
    PageContent(struct PageContent const &) = delete;
    PageContent() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PAGECONTENT
#endif
    MCAPI ~PageContent();
    MCAPI static struct PageContent const BLANK_PAGE;
    MCAPI static struct PageContent read(class CompoundTag const &);
    MCAPI static void write(struct PageContent const &, class CompoundTag &);

};