// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class PerlinNoise {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PERLINNOISE
public:
    class PerlinNoise& operator=(class PerlinNoise const &) = delete;
    PerlinNoise(class PerlinNoise const &) = delete;
    PerlinNoise() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PERLINNOISE
#endif
    MCAPI PerlinNoise(unsigned int, int, int);
    MCAPI void getRegion(float *, class Vec3 const &, int, int, int, class Vec3 const &) const;
    MCAPI float getValue(class Vec3 const &) const;

//private:
    MCAPI void _init(class Random &);

private:

};