// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace PlayerMovement {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI bool isFlying(struct IPlayerMovementProxy const &);
    MCAPI bool isHoloRealityMode(struct IPlayerMovementProxy const &);
    MCAPI void updatePlayerOnInput(struct IPlayerMovementProxy &, class MoveInputHandler &, class Vec3 &);
    MCAPI void updatePlayerRiding(struct IPlayerMovementProxy &, class MoveInputHandler &);
    MCAPI void updateSwimTravel(struct IPlayerMovementProxy &, class MoveInputHandler &, class Vec3 &);

};