// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace QuerySetIdentifier {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI class gsl::span<class HashedString const, -1> getDefaultCollection();
    MCAPI class gsl::span<class HashedString const, -1> getTagsCollection();

};