// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class RegistryKey {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_REGISTRYKEY
public:
    class RegistryKey& operator=(class RegistryKey const &) = delete;
    RegistryKey(class RegistryKey const &) = delete;
    RegistryKey() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_REGISTRYKEY
#endif
    MCAPI bool readValue(char const *, std::string &) const;
    MCAPI ~RegistryKey();

};