// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct RuntimeIdentifierDescription {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RUNTIMEIDENTIFIERDESCRIPTION
public:
    struct RuntimeIdentifierDescription& operator=(struct RuntimeIdentifierDescription const &) = delete;
    RuntimeIdentifierDescription(struct RuntimeIdentifierDescription const &) = delete;
    RuntimeIdentifierDescription() = delete;
#endif
public:
    /*0*/ virtual ~RuntimeIdentifierDescription();
    /*1*/ virtual char const * getJsonName() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RUNTIMEIDENTIFIERDESCRIPTION
#endif

};