// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SavedData {

#define AFTER_EXTRA
public:
    void** __vftable /*VFT*/;
    bool mDirty;
    std::string mId;
#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SAVEDDATA
public:
    class SavedData& operator=(class SavedData const &) = delete;
    SavedData(class SavedData const &) = delete;
    SavedData() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SAVEDDATA
#endif

};