// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScoreboardIdentityRef {

#define AFTER_EXTRA
public:
    enum IdentityDefinition::Type getIdentityType(){
        //ServerScoreboard::_unpackIdentityDefToScorePacket Line30~31 16+72
        return dAccess<enum IdentityDefinition::Type>(this, 88);
    };

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCOREBOARDIDENTITYREF
public:
    class ScoreboardIdentityRef& operator=(class ScoreboardIdentityRef const &) = delete;
    ScoreboardIdentityRef(class ScoreboardIdentityRef const &) = delete;
    ScoreboardIdentityRef() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCOREBOARDIDENTITYREF
#endif
    MCAPI std::string const & getName(class std::function<std::string const & (struct ActorUniqueID)> const &) const;
    MCAPI bool modifyScoreInObjective(int &, class Objective &, int, enum PlayerScoreSetFunction);
    MCAPI bool removeFromObjective(class Scoreboard &, class Objective &);
    MCAPI static class ScoreboardIdentityRef const Undefined;
    MCAPI static std::unique_ptr<class CompoundTag> serialize(class ScoreboardIdentityRef const &);

};