// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"
#include "ScriptBlockContainerComponent.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptLevelTickingAreasComponent : public ScriptBlockContainerComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTLEVELTICKINGAREASCOMPONENT
public:
    class ScriptLevelTickingAreasComponent& operator=(class ScriptLevelTickingAreasComponent const &) = delete;
    ScriptLevelTickingAreasComponent(class ScriptLevelTickingAreasComponent const &) = delete;
    ScriptLevelTickingAreasComponent() = delete;
#endif

public:
    /*0*/ virtual ~ScriptLevelTickingAreasComponent();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual bool applyComponentTo(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class ScriptServerContext &, class Level &, class ScriptApi::ScriptObjectHandle const &) const;
    /*4*/ virtual void __unk_vfn_4();
    /*6*/ virtual bool retrieveComponentFrom(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class ScriptServerContext &, class Level &, class ScriptApi::ScriptObjectHandle &) const;
    /*9*/ virtual bool hasComponent(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class ScriptServerContext &, class Level &, bool &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTLEVELTICKINGAREASCOMPONENT
    MCVAPI bool hasComponent(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class ScriptServerContext &, class Actor &, bool &) const;
#endif

//private:

private:
    MCAPI static class HashedString const mHash;

};