// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ScriptServerActorCarriedItemChangedEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSERVERACTORCARRIEDITEMCHANGEDEVENT
public:
    struct ScriptServerActorCarriedItemChangedEvent& operator=(struct ScriptServerActorCarriedItemChangedEvent const &) = delete;
    ScriptServerActorCarriedItemChangedEvent(struct ScriptServerActorCarriedItemChangedEvent const &) = delete;
    ScriptServerActorCarriedItemChangedEvent() = delete;
#endif
public:
    /*0*/ virtual ~ScriptServerActorCarriedItemChangedEvent();
    /*1*/ virtual bool _serialize(class ScriptEngine &, class ScriptApi::ScriptObjectHandle &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSERVERACTORCARRIEDITEMCHANGEDEVENT
#endif

//private:

};