// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ScriptServerActorUseItemEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSERVERACTORUSEITEMEVENT
public:
    struct ScriptServerActorUseItemEvent& operator=(struct ScriptServerActorUseItemEvent const &) = delete;
    ScriptServerActorUseItemEvent(struct ScriptServerActorUseItemEvent const &) = delete;
    ScriptServerActorUseItemEvent() = delete;
#endif
public:
    /*0*/ virtual ~ScriptServerActorUseItemEvent();
    /*1*/ virtual bool _serialize(class ScriptEngine &, class ScriptApi::ScriptObjectHandle &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSERVERACTORUSEITEMEVENT
#endif

//private:

};