// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptServerActorEventListener {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSERVERACTOREVENTLISTENER
public:
    class ScriptServerActorEventListener& operator=(class ScriptServerActorEventListener const &) = delete;
    ScriptServerActorEventListener(class ScriptServerActorEventListener const &) = delete;
    ScriptServerActorEventListener() = delete;
#endif

public:
    /*0*/ virtual ~ScriptServerActorEventListener();
    /*1*/ virtual enum EventResult onActorAttack(class Actor &, class Actor &, int);
    /*2*/ virtual enum EventResult onActorHurt(struct ActorHurtEvent const &);
    /*3*/ virtual enum EventResult onActorMove(class Actor &, class Vec3 const &);
    /*4*/ virtual void __unk_vfn_4();
    /*5*/ virtual enum EventResult onActorTick(class Actor &);
    /*6*/ virtual enum EventResult onActorSneakChanged(class Actor &, bool);
    /*7*/ virtual enum EventResult onActorStartRiding(class Actor &, class Actor &);
    /*8*/ virtual enum EventResult onActorStopRiding(class Actor &, bool, bool, bool);
    /*9*/ virtual enum EventResult onActorDeath(class Actor &, class ActorDamageSource const &, enum ActorType);
    /*10*/ virtual enum EventResult onActorDefinitionEventTriggered(struct ActorDefinitionEvent const &);
    /*11*/ virtual enum EventResult onActorUseItem(class Actor &, class ItemInstance const &, enum ItemUseMethod);
    /*12*/ virtual void __unk_vfn_12();
    /*13*/ virtual enum EventResult onActorCreated(class Actor &);
    /*14*/ virtual enum EventResult onProjectileHit(struct ProjectileHitEvent const &);
    /*15*/ virtual void __unk_vfn_15();
    /*16*/ virtual void __unk_vfn_16();
    /*17*/ virtual enum EventResult onActorAcquiredItem(class Actor &, class ItemInstance const &, unsigned int, enum ItemAcquisitionMethod, class Actor *);
    /*18*/ virtual void __unk_vfn_18();
    /*19*/ virtual enum EventResult onActorDroppedItem(class Actor &, class ItemInstance const &);
    /*20*/ virtual enum EventResult onActorCarriedItemChanged(class Actor &, class ItemInstance const &, class ItemInstance const &, enum HandSlot);
    /*21*/ virtual enum EventResult onActorEquippedArmor(class Actor &, class ItemInstance const &, enum ArmorSlot);
    /*22*/ virtual enum EventResult onActorRemoved(class Actor &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSERVERACTOREVENTLISTENER
#endif

};