// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptLevelBinderComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTLEVELBINDERCOMPONENT
public:
    class ScriptLevelBinderComponent& operator=(class ScriptLevelBinderComponent const &) = delete;
    ScriptLevelBinderComponent(class ScriptLevelBinderComponent const &) = delete;
    ScriptLevelBinderComponent() = delete;
#endif

public:
    /*0*/ virtual ~ScriptLevelBinderComponent();
    /*1*/ virtual bool serialize(class ScriptEngine &, class ScriptApi::ScriptObjectHandle const &) const;
    /*2*/ virtual bool deserialize(class ScriptEngine &, class ScriptApi::ScriptObjectHandle const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTLEVELBINDERCOMPONENT
#endif
    MCAPI static std::string const TAG;

};