// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptDimensionBinderComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTDIMENSIONBINDERCOMPONENT
public:
    class ScriptDimensionBinderComponent& operator=(class ScriptDimensionBinderComponent const &) = delete;
    ScriptDimensionBinderComponent(class ScriptDimensionBinderComponent const &) = delete;
    ScriptDimensionBinderComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTDIMENSIONBINDERCOMPONENT
#endif
    MCAPI static std::string const TAG;

};