// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptBinderActorTickingAreaTemplate {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTBINDERACTORTICKINGAREATEMPLATE
public:
    class ScriptBinderActorTickingAreaTemplate& operator=(class ScriptBinderActorTickingAreaTemplate const &) = delete;
    ScriptBinderActorTickingAreaTemplate(class ScriptBinderActorTickingAreaTemplate const &) = delete;
    ScriptBinderActorTickingAreaTemplate() = delete;
#endif

public:
    /*0*/ virtual ~ScriptBinderActorTickingAreaTemplate();
    /*1*/ virtual std::string const & getTemplateIdentifier() const;
    /*2*/ virtual void applyTemplate(class ScriptObjectBinder &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTBINDERACTORTICKINGAREATEMPLATE
#endif
    MCAPI static std::unique_ptr<class ScriptObjectBinder> build(class ITickingArea const &);
    MCAPI static std::unique_ptr<class ScriptObjectBinder> build(struct ActorUniqueID const &);

};