// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptBinderItemActorTemplate {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTBINDERITEMACTORTEMPLATE
public:
    class ScriptBinderItemActorTemplate& operator=(class ScriptBinderItemActorTemplate const &) = delete;
    ScriptBinderItemActorTemplate(class ScriptBinderItemActorTemplate const &) = delete;
    ScriptBinderItemActorTemplate() = delete;
#endif

public:
    /*0*/ virtual ~ScriptBinderItemActorTemplate();
    /*1*/ virtual std::string const & getTemplateIdentifier() const;
    /*2*/ virtual void applyTemplate(class ScriptObjectBinder &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTBINDERITEMACTORTEMPLATE
#endif
    MCAPI static std::unique_ptr<class ScriptObjectBinder> build(class entt::basic_registry<enum entt::entity> &, class ItemActor const &);

};