// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SequenceBehaviorNode {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SEQUENCEBEHAVIORNODE
public:
    class SequenceBehaviorNode& operator=(class SequenceBehaviorNode const &) = delete;
    SequenceBehaviorNode(class SequenceBehaviorNode const &) = delete;
    SequenceBehaviorNode() = delete;
#endif

public:
    /*0*/ virtual ~SequenceBehaviorNode();
    /*1*/ virtual enum BehaviorStatus tick(class Actor &);
    /*2*/ virtual void initializeFromDefinition(class Actor &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SEQUENCEBEHAVIORNODE
#endif

};