// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ServerInstanceEventListener {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SERVERINSTANCEEVENTLISTENER
public:
    class ServerInstanceEventListener& operator=(class ServerInstanceEventListener const &) = delete;
    ServerInstanceEventListener(class ServerInstanceEventListener const &) = delete;
    ServerInstanceEventListener() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SERVERINSTANCEEVENTLISTENER
    MCVAPI enum class EventResult onLeaveGameDone(class ServerInstance &);
    MCVAPI enum class EventResult onServerInitializeEnd(class ServerInstance &);
    MCVAPI enum class EventResult onServerInitializeStart(class ServerInstance &);
    MCVAPI enum class EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    MCVAPI enum class EventResult onServerMinecraftInitialized(class ServerInstance &, class Minecraft &);
    MCVAPI enum class EventResult onServerResume(class ServerInstance &);
    MCVAPI enum class EventResult onServerSuspend(class ServerInstance &);
    MCVAPI enum class EventResult onServerThreadStarted(class ServerInstance &);
    MCVAPI enum class EventResult onServerThreadStopped(class ServerInstance &);
    MCVAPI enum class EventResult onServerUpdateEnd(class ServerInstance &);
    MCVAPI enum class EventResult onServerUpdateStart(class ServerInstance &);
    MCVAPI enum class EventResult onStartLeaveGame(class ServerInstance &);
#endif

};