// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace SharedConstants {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI extern int const AutomationProtocolVersion;
    MCAPI extern int const CompanionAppProtocolVersion;
    MCAPI extern class SemVersion const CurrentGameSemVersion;
    MCAPI extern enum class LevelChunkFormat const CurrentLevelChunkFormat;
    MCAPI extern enum class StorageVersion const CurrentStorageVersion;
    MCAPI extern enum class SubChunkFormat const CurrentSubChunkFormat;
    MCAPI extern bool const IsBeta;
    MCAPI extern int const MajorVersion;
    MCAPI extern class GameVersion const MinimumCompatibleGameVersionForLevelData;
    MCAPI extern int const MinorVersion;
    MCAPI extern unsigned short const NetworkDefaultGamePort;
    MCAPI extern unsigned short const NetworkDefaultGamePortv6;
    MCAPI extern int const NetworkDefaultMaxConnections;
    MCAPI extern unsigned short const NetworkEphemeralPort;
    MCAPI extern int const NetworkProtocolVersion;
    MCAPI extern int const PatchVersion;
    MCAPI extern int const RevisionVersion;

};