// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct Shareable {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SHAREABLE
public:
    struct Shareable& operator=(struct Shareable const &) = delete;
    Shareable(struct Shareable const &) = delete;
    Shareable() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SHAREABLE
#endif
    MCAPI void setCraftInto(std::string const &);
    MCAPI void setItem(std::string const &);

};