// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ShieldItemUtils {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SHIELDITEMUTILS
public:
    class ShieldItemUtils& operator=(class ShieldItemUtils const &) = delete;
    ShieldItemUtils(class ShieldItemUtils const &) = delete;
    ShieldItemUtils() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SHIELDITEMUTILS
#endif

//private:

private:
    MCAPI static std::vector<enum ActorDamageCause> const mAlwaysBlockableDamageCauses;

};