// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "StructurePiece.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ShipwreckPiece : public StructurePiece {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SHIPWRECKPIECE
public:
    class ShipwreckPiece& operator=(class ShipwreckPiece const &) = delete;
    ShipwreckPiece(class ShipwreckPiece const &) = delete;
    ShipwreckPiece() = delete;
#endif

public:
    /*0*/ virtual ~ShipwreckPiece();
    /*3*/ virtual enum StructurePieceType getType() const;
    /*5*/ virtual bool postProcess(class BlockSource &, class Random &, class BoundingBox const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SHIPWRECKPIECE
#endif

//private:

private:
    MCAPI static std::string const STRUCTURE_SHIPWRECK_TYPES[];

};