// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Command.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SpawnPointCommand : public Command {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SPAWNPOINTCOMMAND
public:
    class SpawnPointCommand& operator=(class SpawnPointCommand const &) = delete;
    SpawnPointCommand(class SpawnPointCommand const &) = delete;
    SpawnPointCommand() = delete;
#endif

public:
    /*0*/ virtual ~SpawnPointCommand();
    /*1*/ virtual void execute(class CommandOrigin const &, class CommandOutput &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SPAWNPOINTCOMMAND
#endif
    MCAPI static void setup(class CommandRegistry &);

};