// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class StompBlockGoal {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_STOMPBLOCKGOAL
public:
    class StompBlockGoal& operator=(class StompBlockGoal const &) = delete;
    StompBlockGoal(class StompBlockGoal const &) = delete;
    StompBlockGoal() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_STOMPBLOCKGOAL
    MCVAPI bool _canReach(class BlockPos const &);
    MCVAPI void _moveToBlock();
    MCVAPI bool canContinueToUse();
    MCVAPI bool canUse();
    MCVAPI bool findTargetBlock();
    MCVAPI bool isValidTarget(class BlockSource &, class BlockPos const &);
    MCVAPI void start();
    MCVAPI void stop();
    MCVAPI void tick();
#endif

};