// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Command.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class StructureCommand : public Command {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_STRUCTURECOMMAND
public:
    class StructureCommand& operator=(class StructureCommand const &) = delete;
    StructureCommand(class StructureCommand const &) = delete;
    StructureCommand() = delete;
#endif

public:
    /*0*/ virtual ~StructureCommand();
    /*1*/ virtual void execute(class CommandOrigin const &, class CommandOutput &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_STRUCTURECOMMAND
#endif
    MCAPI static void setup(class CommandRegistry &);

//private:
    MCAPI std::string _getFullName() const;
    MCAPI bool _isValidSize(class BlockPos const &, class CommandOutput &) const;
    MCAPI void _load(class CommandOrigin const &, class CommandOutput &) const;
    MCAPI void _save(class CommandOrigin const &, class CommandOutput &) const;

private:

};