// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class StructureManager {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_STRUCTUREMANAGER
public:
    class StructureManager& operator=(class StructureManager const &) = delete;
    StructureManager(class StructureManager const &) = delete;
    StructureManager() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_STRUCTUREMANAGER
#endif
    MCAPI class StructureTemplate & getOrCreate(std::string const &);
    MCAPI class LegacyStructureTemplate & getOrCreateLegacy(std::string const &);
    MCAPI class StructureTemplate * getStructure(std::string const &) const;
    MCAPI bool load(class StructureTemplate &, class ResourcePackManager const *, class LevelStorage *);
    MCAPI bool loadLegacy(class LegacyStructureTemplate &, std::string &);
    MCAPI void loadPlacementQueue(class LevelStorage &, class Level &, class Dimension &);
    MCAPI void loadPlacementQueueItem(std::string const &, class CompoundTag const &, class Level &, class Dimension &);
    MCAPI void queueLoad(std::unique_ptr<class StructureAnimationData>);
    MCAPI bool readStructure(class StructureTemplate &);
    MCAPI void saveToLevel(class StructureTemplate const &, class LevelStorage &);
    MCAPI void tick(class Dimension const &);

//private:
    MCAPI class StructureTemplate * _createAndLoadStructure(std::string const &, class ResourcePackManager const *, class LevelStorage *);
    MCAPI std::string _createLevelStorageId(std::string const &, std::string const &);
    MCAPI class LegacyStructureTemplate * _getLegacy(std::string const &);
    MCAPI bool _placeSegment(class StructureAnimationData &);
    MCAPI class LegacyStructureTemplate * _readLegacyStructure(std::string const &);
    MCAPI void _savePlacementQueueItem(std::string const &, class StructureAnimationData &);

private:
    MCAPI static char const * BEHAVIOR_PACK_STRUCTURES_FOLDER;
    MCAPI static char const * LEVEL_STORAGE_STRUCTURE_TEMPLATE_PREFIX;

};