// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct SurfaceMaterialAttributes {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SURFACEMATERIALATTRIBUTES
public:
    struct SurfaceMaterialAttributes& operator=(struct SurfaceMaterialAttributes const &) = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SURFACEMATERIALATTRIBUTES
#endif
    MCAPI SurfaceMaterialAttributes(struct SurfaceMaterialAttributes const &);
    MCAPI SurfaceMaterialAttributes(struct SurfaceMaterialAttributes &&);
    MCAPI SurfaceMaterialAttributes();
    MCAPI struct SurfaceMaterialAttributes & operator=(struct SurfaceMaterialAttributes &&);
    MCAPI ~SurfaceMaterialAttributes();

};