// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class TargetNearbySystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_TARGETNEARBYSYSTEM
public:
    class TargetNearbySystem& operator=(class TargetNearbySystem const &) = delete;
    TargetNearbySystem(class TargetNearbySystem const &) = delete;
    TargetNearbySystem() = delete;
#endif

public:
    /*0*/ virtual ~TargetNearbySystem();
    /*1*/ virtual void tick(class EntityRegistry &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_TARGETNEARBYSYSTEM
#endif

};