// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "SpikeFeature.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace TheEndSpikeHelper {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI std::vector<class SpikeFeature::EndSpike> getSpikesForLevel(class Level &);

};