// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Enchant.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class TridentLoyaltyEnchant : public Enchant {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_TRIDENTLOYALTYENCHANT
public:
    class TridentLoyaltyEnchant& operator=(class TridentLoyaltyEnchant const &) = delete;
    TridentLoyaltyEnchant(class TridentLoyaltyEnchant const &) = delete;
    TridentLoyaltyEnchant() = delete;
#endif

public:
    /*0*/ virtual ~TridentLoyaltyEnchant();
    /*2*/ virtual int getMinCost(int) const;
    /*3*/ virtual int getMaxCost(int) const;
    /*5*/ virtual int getMaxLevel() const;
    /*10*/ virtual void __unk_vfn_10();
    /*11*/ virtual void __unk_vfn_11();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_TRIDENTLOYALTYENCHANT
#endif

};