// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class VanillaBastionJigsawStructureElements {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_VANILLABASTIONJIGSAWSTRUCTUREELEMENTS
public:
    class VanillaBastionJigsawStructureElements& operator=(class VanillaBastionJigsawStructureElements const &) = delete;
    VanillaBastionJigsawStructureElements(class VanillaBastionJigsawStructureElements const &) = delete;
    VanillaBastionJigsawStructureElements() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_VANILLABASTIONJIGSAWSTRUCTUREELEMENTS
#endif
    MCAPI static void initialize(class StructureManager &, class FeatureRegistry &, class JigsawStructureRegistry &);

};