// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace VanillaBlockConversion {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI class WeakPtr<class BlockLegacy> getBlockTypeFromLegacyId(unsigned int);
    MCAPI int getBlockTypeLegacyIdFromName(std::string const &);
    MCAPI class Block const * tryGetLegacyState(unsigned int, unsigned int);

};