// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class WebToken {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WEBTOKEN
public:
    class WebToken& operator=(class WebToken const &) = delete;
    WebToken() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WEBTOKEN
#endif
    MCAPI WebToken(std::string);
    MCAPI WebToken(class WebToken const &);
    MCAPI std::string toString() const;
    MCAPI bool verifyWithIncludedKey(std::vector<std::string> const &) const;
    MCAPI ~WebToken();
    MCAPI static std::unique_ptr<class WebToken> createFromData(class Json::Value const &, class PrivateKeyManager const &);

//private:
    MCAPI void _parse(class Json::Value &, std::string const &);
    MCAPI std::string _signatureToDER() const;
    MCAPI static std::string _DERToBinary(std::string const &, int);

private:

};