// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class WorldGenClimateMappingAttributes {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WORLDGENCLIMATEMAPPINGATTRIBUTES
public:
    class WorldGenClimateMappingAttributes& operator=(class WorldGenClimateMappingAttributes const &) = delete;
    WorldGenClimateMappingAttributes(class WorldGenClimateMappingAttributes const &) = delete;
    WorldGenClimateMappingAttributes() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WORLDGENCLIMATEMAPPINGATTRIBUTES
#endif
    MCAPI ~WorldGenClimateMappingAttributes();

};