// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ZlibFileAccessWrapper {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ZLIBFILEACCESSWRAPPER
public:
    class ZlibFileAccessWrapper& operator=(class ZlibFileAccessWrapper const &) = delete;
    ZlibFileAccessWrapper(class ZlibFileAccessWrapper const &) = delete;
    ZlibFileAccessWrapper() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ZLIBFILEACCESSWRAPPER
#endif
    MCAPI ZlibFileAccessWrapper(class IFileAccess *);
    MCAPI ~ZlibFileAccessWrapper();

};